### ISSUE TITLE
I should be able to tail multiple files

### ISSUE THREAD

**Issue by mjallday** [balanced-ops/ansible-fluentd#2]
Please ensure that it's possible for me to configure fluent to tail multiple files.

Consider the syntax we developed for configuring ansible via chef

https://github.com/balanced-cookbooks/balanced-fluentd/blob/master/.kitchen.yml#L47-L62

``` yaml

---
vars: 
   - logs_to_tail: 
      - /var/log/balanced/access.log
      - /var/log/precog/access.log
roles:
  - {role: fluentd, tags: [ client ] }
```
